spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/scriptopia
    username: root      # PostgreSQL에서 설정 계정
    password: tiger     # 비밀번호
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb://root:tiger@localhost:27017/scriptopia_mongo?authSource=admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_NAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

auth:
  jwt:
    issuer: scriptopia
    access-exp-seconds: 1800
    refresh-exp-seconds: 1209600
    secret: ${JWT_SECRET}

