version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: scriptopia-postgres
    environment:
      POSTGRES_USER: scriptopia
      POSTGRES_PASSWORD: tiger
      POSTGRES_DB: scriptopia
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data